version: '3.8'
services:
  fuse-provider-upload:
    container_name: fuse-provider-upload
    build: .
    env_file: .env
    ports:
        - ${API_PORT}:8000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./config/service_info.json:/app/service_info.json
        - ./data:/app/data
    expose:
      - ${API_PORT}

  tx-persistence:
    container_name: tx-persistence
    image: txscience/tx-persistence
    restart: always
    env_file:
      - .env
    expose:
      - 27017
      - 27018
      - 27019
