version: '3.8'

services:
  fuse-provider-upload:
    container_name: ${CONTAINER_NAME}
    build: .
    restart: always
    env_file: .env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/service_info.json:/app/service_info.json
      - upload-data:/app/data
    networks:
      - upload_network

  upload-tx-persistence:
    container_name: upload-tx-persistence
    image: txscience/tx-persistence
    restart: always
    env_file:
      - .env
    volumes:
      - upload-tx-persistence-db:/data/db
    expose:
      - 27017
      - 27018
      - 27019
    networks:
      - upload_network

networks:
  upload_network:
    name: ${CONTAINER_NETWORK}
    external: true

volumes:
  upload-tx-persistence-db:
    name: upload-tx-persistence-db
  upload-data:
    name: upload-data
